name: Test2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    env:
      DOCKER_HOST: unix:///var/run/docker-nvme.sock
    steps:
      - name: Echo
        run: echo "has env block"